CREATE DATABASE dtj_db;
USE dtj_db;

CREATE TABLE user(
id INT NOT NULL AUTO_INCREMENT,
username VARCHAR(255) NOT NULL,
password VARCHAR(255) NOT NULL,
CONSTRAINT user_pk PRIMARY KEY (id))
ENGINE=InnoDB DEFAULT CHARSET=utf8;

DESC user;
